/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Projet;

import ag.AgentCentral;
import ag.data;
import jade.core.ProfileImpl;
import jade.gui.GuiEvent;
import jade.util.ExtendedProperties;
import jade.util.leap.Properties;
import jade.wrapper.AgentController;
import jade.wrapper.ControllerException;
import jade.wrapper.StaleProxyException;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.Date;
import java.util.HashMap;
import java.util.Map;
import java.util.concurrent.TimeUnit;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JTable;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ABEDSSAMED
 */
public class MAINFrame extends javax.swing.JFrame {

    /**
     * Creates new form Client_Forme
     */
    public static DefaultTableModel tableModel = new DefaultTableModel();

    public MAINFrame() {
        data d=new data();
        d.initData();
        initComponents();
        String[] columns = {
            "Name", "Prix",
            "Quantite", "Magasin"};
        tableModel = new DefaultTableModel(columns, 0);
        table.setModel(tableModel);
        DateTimeFormatter dtf = DateTimeFormatter.ofPattern("yyyy/MM/dd");
        LocalDateTime now = LocalDateTime.now();
        dateT.setText(dtf.format(now));

    }
    private String NomeArticle;

    private String Colueur;
    private int Qte;
    private float prixMax;

    public String getNomeArticle() {
        return NomeArticle;
    }

    public float getPrixMax() {
        return prixMax;
    }

    public String getColueur() {
        return Colueur;
    }

    public int getQte() {
        return Qte;
    }

//    static String[][] M1 = new String[][]{{"Margherita", "3", "100", "0.5"}, {"Margherita", "3", "100", "0.5"},
//    {"Margherita", "3", "100", "0.5"},
//    {"White_Pizza", "3", "100", "0.5"},
//    {"White_Broccoli", "3", "100", "0.5"},
//    {"Eggplant_Tomato", "3", "100", "0.5"},
//    {"Supreme", "3", "100", "0.5"},
//    {"Supreme", "3", "100", "0.5"},
//    {"Ziti_Pizza", "3", "100", "0.5"},
//    {"Ziti_Pizza", "3", "100", "0.5"},
//    {"Veggie", "3", "100", "0.5"},
//    {"Black_Olives", "3", "100", "0.5"}
//    };
//    static String[][] M2 = new String[][]{{"Margherita", "3", "100", "0.5"}, {"Margherita", "3", "100", "0.5"},
//    {"Margherita", "3", "100", "0.5"},
//    {"White_Pizza", "3", "100", "0.5"},
//    {"White_Broccoli", "3", "100", "0.5"},
//    {"Eggplant_Tomato", "3", "100", "0.5"},
//    {"Supreme", "3", "100", "0.5"},
//    {"Supreme", "3", "100", "0.5"},
//    {"Ziti_Pizza", "3", "100", "0.5"},
//    {"Ziti_Pizza", "3", "100", "0.5"},
//    {"Veggie", "3", "100", "0.5"},
//    {"Black_Olives", "7", "150", "0.5"}
//    };
//    static String[][] M3 = new String[][]{{"Margherita", "4", "100", "0"}, {"Margherita", "3", "100", "0.5"},
//    {"Margherita", "3", "100", "0"},
//    {"White_Pizza", "3", "200", "0"},
//    {"White_Broccoli", "7", "150", "0.5"},
//    {"Eggplant_Tomato", "3", "200", "0.5"},
//    {"Supreme", "7", "100", "0.5"},
//    {"Supreme", "3", "110", "0"},
//    {"Ziti_Pizza", "3", "110", "0.5"},
//    {"Ziti_Pizza", "3", "100", "0.5"},
//    {"Veggie", "3", "100", "0.5"},
//    {"Black_Olives", "4", "170", "0.5"}
//    };
    public void showMsg(Object QTE, boolean vide) {
        // "Magsin ", "Pizza Type", "Price", "Quantity", "Reduction"
//         if(vide){
//            tableModel.addRow(new String[]{msg,PizzaType,QTE,Price}); 
//         }else{
//             
//         }
        textPane.append((String) QTE + "\n");

    }
    static String PizzaName = "";

    static String Sender = "";

    public void getSender(String sed) {
        this.Sender = sed;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        Fresh_Basil1 = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        srt = new javax.swing.JLabel();
        Spinach = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        Onion = new javax.swing.JComboBox<>();
        jLabel16 = new javax.swing.JLabel();
        Pepper = new javax.swing.JComboBox<>();
        jLabel17 = new javax.swing.JLabel();
        Mushroom = new javax.swing.JComboBox<>();
        Mozzarella = new javax.swing.JComboBox<>();
        CheeseRomano = new javax.swing.JComboBox<>();
        tomato = new javax.swing.JComboBox<>();
        Sausage = new javax.swing.JComboBox<>();
        Black_Olives_Red_Sauce = new javax.swing.JComboBox<>();
        Broccoli = new javax.swing.JComboBox<>();
        Eggplant = new javax.swing.JComboBox<>();
        Ricotta = new javax.swing.JComboBox<>();
        jLabel18 = new javax.swing.JLabel();
        Ziti = new javax.swing.JComboBox<>();
        searchButton = new javax.swing.JToggleButton();
        jLabel2 = new javax.swing.JLabel();
        buyButton = new javax.swing.JToggleButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        textPane = new javax.swing.JTextArea();
        jLabel19 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        newBuy = new javax.swing.JToggleButton();
        priceLabel = new javax.swing.JLabel();
        promoLabel = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        spinner = new javax.swing.JSpinner();
        jLabel13 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        dateT = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(102, 0, 204));

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Ingredients ");

        jPanel3.setBackground(new java.awt.Color(102, 0, 204));

        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel3.setText("Black_Olives_Red_Sauce");

        jLabel4.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel4.setText("Ricotta :");

        jLabel7.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel7.setText("Mozzarella :");

        jLabel8.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel8.setText("Broccoli :");

        jLabel9.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel9.setText("Sausage :");

        Fresh_Basil1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "yes", "no" }));
        Fresh_Basil1.setSelectedIndex(1);
        Fresh_Basil1.setToolTipText("");

        jLabel10.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel10.setText("Fresh_Basil :");

        jLabel11.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel11.setText("Eggplant :");

        srt.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        srt.setText("CheeseRomano :");
        srt.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        Spinach.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "yes", "no" }));
        Spinach.setSelectedIndex(1);
        Spinach.setToolTipText("");

        jLabel12.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel12.setText("Spinach :");

        jLabel14.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel14.setText("tomato :");

        jLabel15.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel15.setText("Onion :");

        Onion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "yes", "no" }));
        Onion.setToolTipText("");

        jLabel16.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel16.setText("Pepper :");

        Pepper.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "yes", "no" }));
        Pepper.setToolTipText("");

        jLabel17.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel17.setText("Mushroom :");

        Mushroom.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "yes", "no" }));
        Mushroom.setSelectedIndex(1);
        Mushroom.setToolTipText("");

        Mozzarella.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "yes", "no" }));
        Mozzarella.setToolTipText("");

        CheeseRomano.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "yes", "no" }));
        CheeseRomano.setSelectedIndex(1);
        CheeseRomano.setToolTipText("");
        CheeseRomano.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheeseRomanoActionPerformed(evt);
            }
        });

        tomato.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "yes", "no" }));
        tomato.setSelectedIndex(1);
        tomato.setToolTipText("");
        tomato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tomatoActionPerformed(evt);
            }
        });

        Sausage.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "yes", "no" }));
        Sausage.setToolTipText("");

        Black_Olives_Red_Sauce.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "yes", "no" }));
        Black_Olives_Red_Sauce.setSelectedIndex(1);
        Black_Olives_Red_Sauce.setToolTipText("");

        Broccoli.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "yes", "no" }));
        Broccoli.setSelectedIndex(1);
        Broccoli.setToolTipText("");

        Eggplant.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "yes", "no" }));
        Eggplant.setSelectedIndex(1);
        Eggplant.setToolTipText("");

        Ricotta.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "yes", "no" }));
        Ricotta.setSelectedIndex(1);
        Ricotta.setToolTipText("");

        jLabel18.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel18.setText("Ziti ");

        Ziti.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "yes", "no" }));
        Ziti.setSelectedIndex(1);
        Ziti.setToolTipText("");

        searchButton.setBackground(new java.awt.Color(102, 0, 204));
        searchButton.setText("Searche");
        searchButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.lightGray));
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(srt)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel15)
                                    .addComponent(jLabel16)
                                    .addComponent(jLabel17)
                                    .addComponent(jLabel14)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel18))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Ziti, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tomato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Mushroom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Pepper, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Onion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Fresh_Basil1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Spinach, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Mozzarella, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(CheeseRomano, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Sausage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Black_Olives_Red_Sauce, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Broccoli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Eggplant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Ricotta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(searchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(49, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(37, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(Mozzarella, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(srt)
                            .addComponent(CheeseRomano, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(3, 3, 3)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(tomato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(Spinach, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Sausage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(Black_Olives_Red_Sauce, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(Broccoli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(Eggplant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(Ricotta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(Fresh_Basil1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15)
                    .addComponent(Onion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16)
                    .addComponent(Pepper, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17)
                    .addComponent(Mushroom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel18)
                    .addComponent(Ziti, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(79, 79, 79)
                .addComponent(searchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Liste de produit disponible  ");

        buyButton.setBackground(new java.awt.Color(102, 0, 204));
        buyButton.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        buyButton.setText("Valider");
        buyButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.lightGray));
        buyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buyButtonActionPerformed(evt);
            }
        });

        textPane.setColumns(20);
        textPane.setRows(5);
        jScrollPane3.setViewportView(textPane);

        jLabel19.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(0, 0, 0));
        jLabel19.setText("Les Information d'échange ");

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(table);

        newBuy.setBackground(new java.awt.Color(102, 0, 204));
        newBuy.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        newBuy.setText("Nouveau achat");
        newBuy.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.lightGray));
        newBuy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newBuyActionPerformed(evt);
            }
        });

        priceLabel.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        priceLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        promoLabel.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        promoLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        jLabel6.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Quantity :");

        jLabel13.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setText("Promotion:");

        jLabel20.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(0, 0, 0));
        jLabel20.setText("Prix :");

        dateT.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        dateT.setText("jLabel5");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 786, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel13)
                                .addGap(18, 18, 18)
                                .addComponent(promoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(76, 76, 76))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel2))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(78, 78, 78)
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(spinner, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(26, 26, 26)
                                        .addComponent(newBuy, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(28, 28, 28)
                                        .addComponent(buyButton, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(50, 50, 50)
                                        .addComponent(dateT, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(91, 91, 91)
                                        .addComponent(priceLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel19)
                                .addGap(20, 20, 20)))))
                .addContainerGap())
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(339, 339, 339)
                    .addComponent(jLabel20)
                    .addContainerGap(730, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel19))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(buyButton, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(newBuy, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(40, 40, 40)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel6)
                                    .addComponent(spinner, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(priceLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(promoLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(56, 56, 56)
                                .addComponent(dateT, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 20, Short.MAX_VALUE)))
                .addGap(6, 6, 6))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addContainerGap(431, Short.MAX_VALUE)
                    .addComponent(jLabel20)
                    .addGap(194, 194, 194)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
        String[] columns = {
            "Name", "Prix",
            "Quantite", "Magasin"};
        tableModel = new DefaultTableModel(columns, 0);
        table.setModel(tableModel);

        try {
            jade.core.Runtime rt = jade.core.Runtime.instance();
            Properties p = new ExtendedProperties();
            p.setProperty("gui", "true");
            ProfileImpl pc = new ProfileImpl(p);
            container = rt.createMainContainer(pc);
            container.start();

        } catch (Exception e1) {
            // TODO Auto-generated catch block
            e1.printStackTrace();
        }

        //CENTRAL CONTAINER
        try {
            jade.core.Runtime rt = jade.core.Runtime.instance();
            ProfileImpl pc = new ProfileImpl(false);
            pc.setParameter(ProfileImpl.MAIN_HOST, "localhost");
            jade.wrapper.AgentContainer ac = rt.createAgentContainer(pc);
            agentController1 = ac.createNewAgent("Central", "ag.AgentCentral", new Object[]{});
            agentController1.start();

        } catch (ControllerException e1) {
            // TODO Auto-generated catch block
            e1.printStackTrace();
        }

        //MAGASIN CONTAINER
        try {
            jade.core.Runtime rt = jade.core.Runtime.instance();
            ProfileImpl pc = new ProfileImpl(false);
            pc.setParameter(ProfileImpl.MAIN_HOST, "localhost");
            jade.wrapper.AgentContainer ac = rt.createAgentContainer(pc);
            agentController = ac.createNewAgent("Magasin1", "ag.Magasin1", new Object[]{});
            agentController.start();

        } catch (ControllerException e1) {
            // TODO Auto-generated catch block
            e1.printStackTrace();
        }

        try {
            jade.core.Runtime rt = jade.core.Runtime.instance();
            ProfileImpl pc = new ProfileImpl(false);
            pc.setParameter(ProfileImpl.MAIN_HOST, "localhost");
            jade.wrapper.AgentContainer ac = rt.createAgentContainer(pc);
            agentController2 = ac.createNewAgent("Magasin2", "ag.Magasin2", new Object[]{});
            agentController2.start();

        } catch (ControllerException e1) {
            // TODO Auto-generated catch block
            e1.printStackTrace();
        }

        try {
            jade.core.Runtime rt = jade.core.Runtime.instance();
            ProfileImpl pc = new ProfileImpl(false);
            pc.setParameter(ProfileImpl.MAIN_HOST, "localhost");
            jade.wrapper.AgentContainer ac = rt.createAgentContainer(pc);
            agentController3 = ac.createNewAgent("Magasin3", "ag.Magasin3", new Object[]{});
            agentController3.start();

        } catch (ControllerException e1) {
            // TODO Auto-generated catch block
            e1.printStackTrace();
        }
        searchButton.setEnabled(false);
        searchButton.setEnabled(false);
        Mozzarella.setEnabled(false);
        CheeseRomano.setEnabled(false);
        tomato.setEnabled(false);
        Spinach.setEnabled(false);
        Sausage.setEnabled(false);
        Black_Olives_Red_Sauce.setEnabled(false);
        Broccoli.setEnabled(false);

        Eggplant.setEnabled(false);
        Ricotta.setEnabled(false);
        Fresh_Basil1.setEnabled(false);
        Onion.setEnabled(false);
        Pepper.setEnabled(false);
        Mushroom.setEnabled(false);
        Ziti.setEnabled(false);

        // TODO add your handling code here:
        String Mozzarella1 = Mozzarella.getSelectedItem() + "";
        String CheeseRomano1 = CheeseRomano.getSelectedItem() + "";
        String tomato1 = tomato.getSelectedItem() + "";
        String Spinach1 = Spinach.getSelectedItem() + "";
        String Sausage1 = Sausage.getSelectedItem() + "";
        String Black_Olives_Red_Sauce1 = Black_Olives_Red_Sauce.getSelectedItem() + "";
        String Broccoli1 = Broccoli.getSelectedItem() + "";
        String Eggplant1 = Eggplant.getSelectedItem() + "";
        String Ricotta1 = Ricotta.getSelectedItem() + "";
        String Fresh_Basil1 = MAINFrame.Fresh_Basil1.getSelectedItem() + "";
        String Onion1 = Onion.getSelectedItem() + "";
        String Pepper1 = Pepper.getSelectedItem() + "";
        String Mushroom1 = Mushroom.getSelectedItem() + "";
        String Ziti1 = Ziti.getSelectedItem() + "";

//        GuiEvent gev = new GuiEvent(this, 1);
//        Map<String, Object> params = new HashMap();
//        params.put("Mozzarella1", Mozzarella1);
//        params.put("CheeseRomano1", CheeseRomano1);
//        params.put("Black_Olives_Red_Sauce1", Black_Olives_Red_Sauce1);
//        params.put("Broccoli1", Broccoli1);
//        params.put("Eggplant1", Eggplant1);
//        params.put("tomato1", tomato1);
//        params.put("Ricotta1", Ricotta1);
//        params.put("Sausage1", Sausage1);
//        params.put("Spinach1", Spinach1);
//        params.put("Onion1", Onion1);
//        params.put("Pepper1", Pepper1);
//        params.put("Mushroom1", Mushroom1);
//        params.put("Ziti1", Ziti1);
//        params.put("Fresh_Basil1", Fresh_Basil1);
//        params.put("Quantety", qtet);
//
//        gev.addParameter(params);
//        consAgent.onGuiEvent(gev);

    }//GEN-LAST:event_searchButtonActionPerformed

    private void CheeseRomanoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheeseRomanoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CheeseRomanoActionPerformed

    private void tomatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tomatoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tomatoActionPerformed

    private void buyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buyButtonActionPerformed
        // TODO add your handling code here:
        int selectedProduct = table.getSelectedRow();
        String pp = table.getValueAt(selectedProduct, 0).toString();
        AgentCentral.bought = pp;
        AgentCentral.qt = true;
        AgentCentral.qtBought = (int) spinner.getValue();
        try {
            Thread.sleep(2000);
        } catch (InterruptedException e1) {
            // TODO Auto-generated catch block
            e1.printStackTrace();
        }

        if (table.getValueAt(selectedProduct, 3).toString().equals("Magasin 1")) {
            table.setValueAt(data.infoMagasin1.get(pp).quantity, selectedProduct, 2);

            if (data.infoMagasin1.get(pp).quantity == 0) {
                tableModel.removeRow(selectedProduct);
            }
        }

        if (table.getValueAt(selectedProduct, 3).toString().equals("Magasin 2")) {
            table.setValueAt(data.infoMagasin2.get(pp).quantity, selectedProduct, 2);

            if (data.infoMagasin2.get(pp).quantity == 0) {
                tableModel.removeRow(selectedProduct);
            }
        }

        if (table.getValueAt(selectedProduct, 3).toString().equals("Magasin 3")) {
            table.setValueAt(data.infoMagasin3.get(pp).quantity, selectedProduct, 2);

            if (data.infoMagasin3.get(pp).quantity == 0) {
                tableModel.removeRow(selectedProduct);
            }
        }

    }//GEN-LAST:event_buyButtonActionPerformed
    jade.wrapper.AgentContainer container = null;
    AgentController agentController1 = null;
    AgentController agentController = null;
    AgentController agentController2 = null;
    AgentController agentController3 = null;
    private void newBuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newBuyActionPerformed
        // TODO add your handling code here:
        searchButton.setEnabled(true);
        Mozzarella.setEnabled(true);
        CheeseRomano.setEnabled(true);
        tomato.setEnabled(true);
        Spinach.setEnabled(true);
        Sausage.setEnabled(true);
        Black_Olives_Red_Sauce.setEnabled(true);
        Broccoli.setEnabled(true);

        Eggplant.setEnabled(true);
        Ricotta.setEnabled(true);
        Fresh_Basil1.setEnabled(true);
        Onion.setEnabled(true);
        Pepper.setEnabled(true);
        Mushroom.setEnabled(true);
        Ziti.setEnabled(true);
        try {
            agentController.kill();
            agentController1.kill();
            agentController2.kill();
            agentController3.kill();
            container.kill();
        } catch (StaleProxyException e1) {
            // TODO Auto-generated catch block
            e1.printStackTrace();
        }
        while (tableModel.getRowCount() != 0) {
            tableModel.removeRow(0);
        }
        data.Magasin1.clear();
        data.Magasin2.clear();

        newBuy.setEnabled(false);
        promoLabel.setVisible(false);
        priceLabel.setVisible(false);
    }//GEN-LAST:event_newBuyActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MAINFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MAINFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MAINFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MAINFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        data dd = new data();
        dd.initData();
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MAINFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JComboBox<String> Black_Olives_Red_Sauce;
    public static javax.swing.JComboBox<String> Broccoli;
    public static javax.swing.JComboBox<String> CheeseRomano;
    public static javax.swing.JComboBox<String> Eggplant;
    public static javax.swing.JComboBox<String> Fresh_Basil1;
    public static javax.swing.JComboBox<String> Mozzarella;
    public static javax.swing.JComboBox<String> Mushroom;
    public static javax.swing.JComboBox<String> Onion;
    public static javax.swing.JComboBox<String> Pepper;
    public static javax.swing.JComboBox<String> Ricotta;
    public static javax.swing.JComboBox<String> Sausage;
    public static javax.swing.JComboBox<String> Spinach;
    public static javax.swing.JComboBox<String> Ziti;
    private javax.swing.JToggleButton buyButton;
    private javax.swing.JLabel dateT;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JToggleButton newBuy;
    public static javax.swing.JLabel priceLabel;
    public static javax.swing.JLabel promoLabel;
    private javax.swing.JToggleButton searchButton;
    private javax.swing.JSpinner spinner;
    private javax.swing.JLabel srt;
    public static javax.swing.JTable table;
    public static javax.swing.JTextArea textPane;
    public static javax.swing.JComboBox<String> tomato;
    // End of variables declaration//GEN-END:variables
}
