/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Projet;

import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.SwingUtilities;
import inference.BooleanRuleBase;
import inference.Clause;
import inference.Condition;
import inference.Rule;
import inference.RuleBase;
import inference.RuleVariable;

/**
 *
 * @author ABEDSSAMED
 */
public class PizzaType extends javax.swing.JFrame {

    /**
     * Creates new form PizzaType
     */
    static BooleanRuleBase pizza;

    static RuleBase currentRuleBase;

    public PizzaType() {

        initComponents();
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width / 2 - this.getSize().width / 2, dim.height / 2 - this.getSize().height / 2);
        jTextArea1.setEditable(false);
        TXTInference.setEditable(false);
        try {
            pizza = new BooleanRuleBase("Pizza Rule Base");

        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Fresh_Basil = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        srt = new javax.swing.JLabel();
        Spinach = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        Onion = new javax.swing.JComboBox<>();
        jLabel16 = new javax.swing.JLabel();
        Pepper = new javax.swing.JComboBox<>();
        jLabel17 = new javax.swing.JLabel();
        Mushroom = new javax.swing.JComboBox<>();
        Mozzarella = new javax.swing.JComboBox<>();
        CheeseRomano = new javax.swing.JComboBox<>();
        tomato = new javax.swing.JComboBox<>();
        Sausage = new javax.swing.JComboBox<>();
        Black_Olives_Red_Sauce = new javax.swing.JComboBox<>();
        Broccoli = new javax.swing.JComboBox<>();
        Eggplant = new javax.swing.JComboBox<>();
        Ricotta = new javax.swing.JComboBox<>();
        jLabel18 = new javax.swing.JLabel();
        Ziti = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TXTInference = new javax.swing.JTextArea();
        jLabel13 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(102, 0, 204));

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Pizza  variables ");

        jButton1.setBackground(new java.awt.Color(102, 0, 204));
        jButton1.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Start ");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(102, 0, 204));
        jButton2.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Clear");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel2.setText("Black_Olives_Red_Sauce");

        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel3.setText("Ricotta :");

        jLabel4.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel4.setText("Mozzarella :");

        jLabel5.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel5.setText("Broccoli :");

        jLabel6.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel6.setText("Sausage :");

        Fresh_Basil.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "yes", "no" }));
        Fresh_Basil.setSelectedIndex(1);

        jLabel7.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel7.setText("Fresh_Basil :");

        jLabel8.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel8.setText("Eggplant :");

        srt.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        srt.setText("CheeseRomano :");
        srt.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        Spinach.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "yes", "no" }));
        Spinach.setSelectedIndex(1);

        jLabel11.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel11.setText("Spinach :");

        jLabel14.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel14.setText("tomato :");

        jLabel15.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel15.setText("Onion :");

        Onion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "yes", "no" }));
        Onion.setSelectedIndex(1);

        jLabel16.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel16.setText("Pepper :");

        Pepper.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "yes", "no" }));
        Pepper.setSelectedIndex(1);

        jLabel17.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel17.setText("Mushroom :");

        Mushroom.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "yes", "no" }));
        Mushroom.setSelectedIndex(1);

        Mozzarella.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "yes", "no" }));
        Mozzarella.setSelectedIndex(1);

        CheeseRomano.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "yes", "no" }));
        CheeseRomano.setSelectedIndex(1);
        CheeseRomano.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheeseRomanoActionPerformed(evt);
            }
        });

        tomato.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "yes", "no" }));
        tomato.setSelectedIndex(1);
        tomato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tomatoActionPerformed(evt);
            }
        });

        Sausage.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "yes", "no" }));
        Sausage.setSelectedIndex(1);

        Black_Olives_Red_Sauce.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "yes", "no" }));
        Black_Olives_Red_Sauce.setSelectedIndex(1);

        Broccoli.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "yes", "no" }));
        Broccoli.setSelectedIndex(1);

        Eggplant.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "yes", "no" }));
        Eggplant.setSelectedIndex(1);
        Eggplant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EggplantActionPerformed(evt);
            }
        });

        Ricotta.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "yes", "no" }));
        Ricotta.setSelectedIndex(1);

        jLabel18.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel18.setText("Ziti ");

        Ziti.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "yes", "no" }));
        Ziti.setSelectedIndex(1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(srt)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel15)
                                    .addComponent(jLabel16)
                                    .addComponent(jLabel17)
                                    .addComponent(jLabel14)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel18))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Ziti, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tomato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Mushroom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Pepper, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Onion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Fresh_Basil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Spinach, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Mozzarella, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(CheeseRomano, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Sausage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Black_Olives_Red_Sauce, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Broccoli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Eggplant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Ricotta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(Mozzarella, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(srt)
                            .addComponent(CheeseRomano, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(3, 3, 3)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(tomato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(Spinach, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Sausage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(Black_Olives_Red_Sauce, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(Broccoli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(Eggplant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(Ricotta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(Fresh_Basil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15)
                    .addComponent(Onion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16)
                    .addComponent(Pepper, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17)
                    .addComponent(Mushroom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel18)
                    .addComponent(Ziti, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jLabel10.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("Resultats:");

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        jTextArea1.setRows(5);
        jTextArea1.setText("Pizza  Rule Base Rule Base: \nMargherita: IF tomato=yes \n     AND Mozzarella=yes \n     AND Fresh_Basil=yes  \n     THEN pizza=Margherita \nWhite_Pizza: IF Ricotta=yes \n     AND Mozzarella=yes \n     AND CheeseRomano=yes  \n     THEN pizza=White_Pizza \nWhite_Spinach: IF pizza=White_Pizza \n     AND Spinach=yes \n     THEN pizza=White_Spinach \nWhite_Broccoli: IF pizza=White_Pizza \n     AND Broccoli=yes \n     THEN pizza=White_Broccoli \nEggplant_Tomato: IF pizza=White_Pizza \n     AND tomato=yes \n     AND Eggplant=yes \n     THEN pizza=Eggplant_Tomato \nSupreme: IF Sausage=yes \n     AND Pepper=yes \n     AND Onion=yes \n     AND Mozzarella=yes \n     THEN pizza=Supreme \nZiti_Pizza: IF Ricotta=yes \n     AND CheeseRomano=yes \n     AND ziti=yes \n     AND Mozzarella=yes \n     THEN pizza=Ziti_Pizza \nZiti: IF ziti=yes \n     THEN pizza=Ziti_Pizza \nVeggie: IF Mushroom=yes \n     AND Pepper=yes \n     AND Onion=yes \n     AND Black_Olives_Red_Sauce=yes \n     AND Mozzarella=yes \n     THEN pizza=Veggie \nBlack_Olives: IF Black_Olives_Red_Sauce=yes \n     THEN pizza=Black_Olives ");
        jTextArea1.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        jScrollPane1.setViewportView(jTextArea1);

        jLabel12.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("Base des régles :");

        TXTInference.setBackground(new java.awt.Color(0, 0, 0));
        TXTInference.setColumns(20);
        TXTInference.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        TXTInference.setForeground(new java.awt.Color(255, 255, 255));
        TXTInference.setRows(5);
        jScrollPane2.setViewportView(TXTInference);

        jLabel13.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setText("Moteur d'inférence :");

        jButton5.setBackground(new java.awt.Color(255, 255, 255));
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Projet/Windows_Close_Program_22531 (1).png"))); // NOI18N
        jButton5.setToolTipText("Quitter");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 393, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 393, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(411, 411, 411)
                                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton5))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
  public static void initPizza(BooleanRuleBase rb) {
        RuleVariable Pizza = new RuleVariable(rb, "pizza");
        Pizza.setLabels("Margherita White_Pizza White_Spinach White_Broccoli Eggplant_Tomato Supreme Ziti_Pizza Veggie");
        Pizza.setPromptText("What kind of vehicle is it?");
        RuleVariable Mozzarella = new RuleVariable(rb, "Mozzarella");
        Mozzarella.setLabels("yes no");

        RuleVariable Fresh_Basil = new RuleVariable(rb, "Fresh_Basil");
        Fresh_Basil.setLabels("yes no");

        RuleVariable CheeseRomano = new RuleVariable(rb, "CheeseRomano");
        CheeseRomano.setLabels("yes no");

        RuleVariable Spinach = new RuleVariable(rb, "Spinach");
        Spinach.setLabels("yes no");

        RuleVariable Broccoli = new RuleVariable(rb, "Broccoli");
        Broccoli.setLabels("yes no");

        RuleVariable tomato = new RuleVariable(rb, "tomato");
        tomato.setLabels("yes no");

        RuleVariable Sausage = new RuleVariable(rb, "Sausage");
        Sausage.setLabels("yes no");

        RuleVariable Pepper = new RuleVariable(rb, "Pepper");
        Pepper.setLabels("yes no");

        RuleVariable Onion = new RuleVariable(rb, "Onion");
        Onion.setLabels("yes no");

        RuleVariable ziti = new RuleVariable(rb, "ziti");
        ziti.setLabels("yes no");

        RuleVariable Mushroom = new RuleVariable(rb, "Mushroom");
        Mushroom.setLabels("yes no");

        RuleVariable Black_Olives_Red_Sauce = new RuleVariable(rb, "Black_Olives_Red_Sauce");
        Black_Olives_Red_Sauce.setLabels("yes no");

        RuleVariable Ricotta = new RuleVariable(rb, "Ricotta");
        Ricotta.setLabels("yes no");

        RuleVariable Eggplant = new RuleVariable(rb, "Eggplant");
        Eggplant.setLabels("yes no");

        Condition cEquals = new Condition("=");

        new Rule(rb, "Supreme", new Clause[]{new Clause(Sausage, cEquals, "yes"),
            new Clause(Pepper, cEquals, "yes"),
            new Clause(Onion, cEquals, "yes"),
            new Clause(Mozzarella, cEquals, "yes")},
                new Clause(Pizza, cEquals, "Supreme"));
        new Rule(rb, "Ziti_Pizza", new Clause[]{new Clause(Ricotta, cEquals, "yes"),
            new Clause(CheeseRomano, cEquals, "yes"),
            new Clause(ziti, cEquals, "yes"),
            new Clause(Mozzarella, cEquals, "yes")},
                new Clause(Pizza, cEquals, "Ziti_Pizza"));
        new Rule(rb, "Ziti", new Clause[]{
            new Clause(ziti, cEquals, "yes"),},
                new Clause(Pizza, cEquals, "Ziti_Pizza"));
        new Rule(rb, "Veggie", new Clause[]{new Clause(Mushroom, cEquals, "yes"),
            new Clause(Pepper, cEquals, "yes"),
            new Clause(Onion, cEquals, "yes"),
            new Clause(Black_Olives_Red_Sauce, cEquals, "yes"),
            new Clause(Mozzarella, cEquals, "yes")},
                new Clause(Pizza, cEquals, "Veggie"));
        new Rule(rb, "Black_Olives", new Clause[]{
            new Clause(Black_Olives_Red_Sauce, cEquals, "yes"),},
                new Clause(Pizza, cEquals, "Black_Olives"));
        new Rule(rb, "Margherita", new Clause[]{new Clause(tomato, cEquals, "yes"),
            new Clause(Mozzarella, cEquals, "yes"),
            new Clause(Fresh_Basil, cEquals, "yes ")},
                new Clause(Pizza, cEquals, "Margherita"));
        new Rule(rb, "White_Pizza", new Clause[]{new Clause(Ricotta, cEquals, "yes"),
            new Clause(Mozzarella, cEquals, "yes"),
            new Clause(CheeseRomano, cEquals, "yes ")},
                new Clause(Pizza, cEquals, "White_Pizza"));
        new Rule(rb, "White_Spinach", new Clause[]{new Clause(Pizza, cEquals, "White_Pizza"),
            new Clause(Spinach, cEquals, "yes"),},
                new Clause(Pizza, cEquals, "White_Spinach"));

        new Rule(rb, "White_Broccoli", new Clause[]{new Clause(Pizza, cEquals, "White_Pizza"),
            new Clause(Broccoli, cEquals, "yes")},
                new Clause(Pizza, cEquals, "White_Broccoli"));
        new Rule(rb, "Eggplant_Tomato", new Clause[]{new Clause(Pizza, cEquals, "White_Pizza"),
            new Clause(tomato, cEquals, "yes"),
            new Clause(Eggplant, cEquals, "yes")},
                new Clause(Pizza, cEquals, "Eggplant_Tomato"));
    }

    public void demoPizzaFC(BooleanRuleBase rb) {

        // should be a insect, ladybug
        rb.setVariableValue("Mozzarella", Mozzarella.getSelectedItem().toString());
        System.out.println("mozz " + Mozzarella.getSelectedItem().toString());
        rb.setVariableValue("Fresh_Basil", Fresh_Basil.getSelectedItem().toString());
        System.out.println("fresh " + Fresh_Basil.getSelectedItem().toString());
        rb.setVariableValue("Ricotta", Ricotta.getSelectedItem().toString());
        rb.setVariableValue("CheeseRomano", CheeseRomano.getSelectedItem().toString());
        rb.setVariableValue("Spinach", Spinach.getSelectedItem().toString());
        rb.setVariableValue("Broccoli", Broccoli.getSelectedItem().toString());
        rb.setVariableValue("tomato", tomato.getSelectedItem().toString());
        System.out.println("tomato " + tomato.getSelectedItem().toString());
        rb.setVariableValue("Eggplant", Eggplant.getSelectedItem().toString());
        rb.setVariableValue("Sausage", Sausage.getSelectedItem().toString());
        rb.setVariableValue("Pepper", Pepper.getSelectedItem().toString());
        rb.setVariableValue("Onion", Onion.getSelectedItem().toString());
        rb.setVariableValue("ziti", Ziti.getSelectedItem().toString());
        rb.setVariableValue("Mushroom", Mushroom.getSelectedItem().toString());
        rb.setVariableValue("Black_Olives_Red_Sauce", Black_Olives_Red_Sauce.getSelectedItem().toString());
        rb.setVariableValue("pizza", null);

        rb.displayVariables(TXTInference);
    }
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        initPizza(pizza);
        pizza.setS(0);
        demoPizzaFC(pizza);

        SwingUtilities.updateComponentTreeUI(this.TXTInference);
        currentRuleBase = pizza;
        TXTInference.setText("\n --- Starting Inferencing Cycle --- \n");
        currentRuleBase.forwardChain();
        
        TXTInference.append(" \n  --------- Conflite Set  -------- \n ");
        TXTInference.append("\n " + pizza.getConflit());
        TXTInference.append(" \n --------- Selected Rule  -------- \n ");
        TXTInference.append(pizza.getSelectedRule() + "");

        TXTInference.append("\n --------Target----------\n");

        if (pizza.getVariable("pizza").getValue() != null) {
            TXTInference.append("\n pizza type is: " + pizza.getVariable("pizza").getValue() + "\n --- Ending Inferencing Cycle --- \n ");
        } else {
            TXTInference.append("\n pizza type is: No rule can be applied  \n --- Ending Inferencing Cycle --- \n ");
        }


    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        TXTInference.setText("");
        pizza.setS(0);
        currentRuleBase.reset();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void CheeseRomanoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheeseRomanoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CheeseRomanoActionPerformed

    private void tomatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tomatoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tomatoActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        dispose();
        WelcomeForm W = new WelcomeForm();
        W.show();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void EggplantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EggplantActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EggplantActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PizzaType.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PizzaType.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PizzaType.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PizzaType.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PizzaType().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> Black_Olives_Red_Sauce;
    private javax.swing.JComboBox<String> Broccoli;
    private javax.swing.JComboBox<String> CheeseRomano;
    private javax.swing.JComboBox<String> Eggplant;
    private javax.swing.JComboBox<String> Fresh_Basil;
    private javax.swing.JComboBox<String> Mozzarella;
    private javax.swing.JComboBox<String> Mushroom;
    private javax.swing.JComboBox<String> Onion;
    private javax.swing.JComboBox<String> Pepper;
    private javax.swing.JComboBox<String> Ricotta;
    private javax.swing.JComboBox<String> Sausage;
    private javax.swing.JComboBox<String> Spinach;
    private javax.swing.JTextArea TXTInference;
    private javax.swing.JComboBox<String> Ziti;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel srt;
    private javax.swing.JComboBox<String> tomato;
    // End of variables declaration//GEN-END:variables
}
